version: "3.9"

services:
  fastapi:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - worker
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  worker:
    build:
      context: ./
      dockerfile: Dockerfile.celery.summarizer_worker
    container_name: celery_worker
    restart: always
    depends_on:
      - redis
    #command: celery -A app.worker.celery_app worker --loglevel=info
    environment:
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0

  redis:
    image: redis:7
    container_name: redis_broker
    restart: always
    ports:
      - "6379:6379"
